### ISSUE TITLE
last three tests don't pass

### ISSUE THREAD

**Issue by geluso** [learn-co-curriculum/js-looping-and-iteration-looping-code-along#12]
Student Slack discussion says the last three tests in this lab don't work, even the solution branch doesn't pass.

<img width="433" alt="Screen Shot 2019-04-05 at 9 35 54 AM" src="https://user-images.githubusercontent.com/510868/55642960-c42c9100-5786-11e9-964a-4c729eac5515.png">

**Comment by sgharms** [comment]
As of commit: 638635a7096

If I run `npm test` I get, in my browser:

![image](https://user-images.githubusercontent.com/50019/55915664-1838da80-5bb8-11e9-884e-b841f81d9669.png)

Am I missing something?

**Comment by HyeokJungKim** [comment]
<img width="624" alt="Screen Shot 2019-04-23 at 5 56 21 PM" src="https://user-images.githubusercontent.com/31145202/56618805-9ef6aa00-65f1-11e9-92a7-2b1488be90f8.png">

<img width="815" alt="Screen Shot 2019-04-23 at 5 56 49 PM" src="https://user-images.githubusercontent.com/31145202/56618808-a1590400-65f1-11e9-958c-3030156c98c0.png">

Here are some screenshots of the test not passing.
The code that they wrote was the one they copied and pasted from the Solution Branch.

**Comment by drakeltheryuujin** [comment]
@sgharms this is one of a handful of lessons that pass with the learn-co browser test system but fail when using regular mocha testing. Investigating why this happens.

**Comment by RylanBauermeister** [comment]
So this happens because when you stub Math.random in a mocha file it copies your file-specific version of Math.random that got spun up as a requirement.  It seems this issue also plagues `new Date`, if we use that in any other tests.

Overcoming it is apparently possible, but incredibly crufty.  Here's a git repo walking through the process using `mockery`: https://github.com/newz2000/dice-tdd

My personal recommendation is to change the lab to utilize non-randoms.  It would probably be less work than making this one work, and the amount of additional code interwoven into the normal lines would likely be very confusing for student.

Here's a screenshot of my specific failure pre-attempting to fix it:
<img width="744" alt="Screen Shot 2019-04-25 at 12 31 07 PM" src="https://user-images.githubusercontent.com/38542638/56762979-06c60580-6756-11e9-9897-3f25ee96967a.png">
As you can see, the function is returning different values for numbers of tails flipped pretty consistently, but the test itself isn't stubbing the correct Math.random instance, and therefore is failing to recognize that it is called, or force specific return values.

**Comment by sgharms** [comment]
Good research @RylanBauermeister . It's so strange that it works on some machines but not others, I wonder if the internals of `rand()` have changed between OS versions or some such. In any case, the reversion of the merge commit that brought in the random seems like a good strategy.

**Comment by geluso** [comment]
What causes it to run in the terminal vs running in the browser?

**Comment by sgharms** [comment]
@geluso I believe the learn-browser dependency is the culprit. It's designed to de-scary mocha+chai ecosystem and is set up to look at a virtual DOM as a measure of success (ideal for dom-based challenges). we're testing to see if jettisoning that dep removes the breakage.

**Comment by rrcobb** [comment]
Another example for this issue https://github.com/learn-co-students/js-looping-and-iteration-looping-code-along-nyc-web-career-031119/pull/12

**Comment by maxwellbenton** [comment]
Hey @geluso,

I've pushed up the rewritten content for this lab, removing the reliance on Math.random() and changing the tests and narrative a bit so this should no longer be an issue. Thanks for reporting!

**Comment by geluso** [comment]
Copy that! Saw the PR.
