### ISSUE TITLE
Problem with running test suite

### ISSUE THREAD

**Issue by KatieLars** [learn-co-curriculum/js-looping-and-iteration-looping-code-along#2]
Does not respond to learn submit in the terminal (so it does not show that I have passed the walkthrough). Also, the test suite doesn't open in the simple server. It opens the last localhost:8000 I had open. . .  I've tried quitting and restarting terminal, and it still opens the old lab.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @KatieLars.

We have updated the materials so that this lesson correctly registers as a lab on learn.co and believe your issue to have been resolved. You may need to go to your personal fork of the repository, copy your solution out of index.js, delete the personal fork and revisit the lesson in order for learn.co to display the updated materials.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
