### ISSUE TITLE
Can't open IDE and access lab

### ISSUE THREAD

**Issue by taoliu12** [learn-co-curriculum/js-looping-and-iteration-looping-code-along#3]

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @kev112.

We have updated the materials so that this lesson correctly registers as a lab on learn.co and believe your issue to have been resolved. If you revisit the lesson you should see that learn.co displays lights for forking, testinging and submitting a PR now. If you do not see this, you may need to go to your personal fork of the repository, copy your solution out of index.js, delete the personal fork and revisit the lesson in order for learn.co to display the updated materials.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
