### ISSUE TITLE
Using Math.random() >= 0.5 as opposed to Math.random() < 0.5 Is a hard-coded requirement.

### ISSUE THREAD

**Issue by arye-eidelman** [learn-co-curriculum/js-looping-and-iteration-looping-code-along#6]
I think it should be mentioned in the readme that Using `Math.random() >= 0.5` Is a hard-coded requirement. `Math.random() < 0.5` on the other hand, hangs the page.

This hangs the page instead of passing or failing the test
```javascript
const tailsNeverFails = function(){
  let count = 0
  while(Math.random() < 0.5){
    count++
  }
  return `You got ${count} tails in a row!`
}
```

It works fine in isolation by disabling the tests and running `tailsNeverFails()` in the console.

I'm not exactly sure this is why, some possibilities are:

1. Because Math.random is simulated to return a value more than or equal 0.5 the first 2 and 8 times, if I look for the opposite case when it's less than 0.5 (Math.random() < 0.5) Math.random will only be calld once. leaving the page waiting for me to call Math.random 1 or 7 more times.

2. if math.random is called more then 2 or 8 times it returns 0.2 forever turning my while loop into an infinite loop.

The debugger keeps hanging unpredictable so I'm still not sure where exactly the issue is happening.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @arye-dov-eidelman.

We have updated the readme so that it specifically calls out the need for using Math.random() >= 0.5 so this issue should no longer occur.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
